name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^11.1.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  rxdart: ^0.28.0
  flutter_local_notifications: ^17.2.2
  firebase_auth: ^5.2.0
  firebase_ui_auth: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
